---
- name: Prepare
  hosts: all
  tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true

    - name: Install zigbee2mqtt dependencies
      ansible.builtin.package:
        name:
          - git
          - npm
